name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Update dependencies
      run: |
        npm update
        npm audit fix --force
    
    - name: Run tests after update
      run: npm test -- --watchAll=false
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates.
          
          ### Changes:
          - Updated npm packages to latest compatible versions
          - Applied security fixes via `npm audit fix`
          
          ### Testing:
          - ✅ All tests pass
          - ✅ Build completes successfully
          
          Please review the changes before merging.
        branch: dependency-updates
        delete-branch: true
